"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ArrowLeft } from "lucide-react"
import { useRouter } from "next/navigation"
import RecordedStreamsLibrary from "@/components/grocery/live-shopping/recorded-streams-library"
import { toast } from "@/components/ui/use-toast"
import type { StreamRecording } from "@/types/live-shopping"

export default function RecordingsPage() {
  const router = useRouter()
  const [recordings, setRecordings] = useState<StreamRecording[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    // Simulate loading recordings
    const loadRecordings = async () => {
      // In a real app, this would fetch from an API
      const mockRecordings: StreamRecording[] = [
        {
          id: "rec-1",
          streamId: "stream-1",
          title: "Organic Produce Showcase - Fresh Spring Vegetables",
          description: "Featuring the best organic vegetables of the season with special discounts",
          thumbnailUrl: "/placeholder.svg?height=720&width=1280",
          recordingUrl: "https://example.com/recordings/rec-1.mp4",
          duration: 3600, // 1 hour
          fileSize: 2.5 * 1024 * 1024 * 1024, // 2.5 GB
          startTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
          endTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 3600000).toISOString(),
          isProcessing: false,
          isPublic: true,
          viewCount: 245,
          downloadCount: 12,
          highlights: [
            {
              id: "highlight-1",
              title: "Tomato Tasting",
              startTime: 300,
              endTime: 450,
              thumbnailUrl: "/placeholder.svg?height=360&width=640",
              clipUrl: "https://example.com/clips/highlight-1.mp4",
              viewCount: 89,
              createdBy: "host",
              isAutoGenerated: false,
            },
          ],
          chapters: [
            {
              id: "chapter-1",
              title: "Introduction",
              startTime: 0,
              endTime: 180,
              thumbnailUrl: "/placeholder.svg?height=360&width=640",
            },
            {
              id: "chapter-2",
              title: "Vegetable Showcase",
              startTime: 180,
              endTime: 2400,
              thumbnailUrl: "/placeholder.svg?height=360&width=640",
              productIds: ["prod-1", "prod-2", "prod-3"],
            },
          ],
          quality: "high",
          format: "mp4",
        },
        {
          id: "rec-2",
          streamId: "stream-2",
          title: "Healthy Cooking with Organic Ingredients",
          description: "Live cooking demonstration using fresh organic ingredients",
          thumbnailUrl: "/placeholder.svg?height=720&width=1280",
          recordingUrl: "https://example.com/recordings/rec-2.mp4",
          duration: 2700, // 45 minutes
          fileSize: 1.8 * 1024 * 1024 * 1024, // 1.8 GB
          startTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
          endTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 2700000).toISOString(),
          isProcessing: false,
          isPublic: true,
          viewCount: 187,
          downloadCount: 8,
          highlights: [],
          chapters: [],
          quality: "medium",
          format: "mp4",
        },
        {
          id: "rec-3",
          streamId: "stream-3",
          title: "Farm Tour - Behind the Scenes",
          description: "Virtual tour of our organic farm and growing practices",
          thumbnailUrl: "/placeholder.svg?height=720&width=1280",
          recordingUrl: "https://example.com/recordings/rec-3.mp4",
          duration: 4500, // 1.25 hours
          fileSize: 3.2 * 1024 * 1024 * 1024, // 3.2 GB
          startTime: new Date().toISOString(),
          isProcessing: true,
          isPublic: false,
          viewCount: 0,
          downloadCount: 0,
          highlights: [],
          chapters: [],
          quality: "high",
          format: "mp4",
        },
      ]

      setRecordings(mockRecordings)
      setLoading(false)
    }

    loadRecordings()
  }, [])

  const handlePlayRecording = (recording: StreamRecording) => {
    // In a real app, this would open a video player
    console.log("Playing recording:", recording.title)
  }

  const handleDownloadRecording = (recording: StreamRecording) => {
    toast({
      title: "Download Started",
      description: `Downloading "${recording.title}"...`,
    })
    // In a real app, this would trigger a download
  }

  const handleShareRecording = (recording: StreamRecording) => {
    // In a real app, this would open a share dialog
    navigator.clipboard.writeText(`${window.location.origin}/recordings/${recording.id}`)
    toast({
      title: "Link Copied",
      description: "Recording link copied to clipboard",
    })
  }

  const handleCreateClip = (recording: StreamRecording) => {
    toast({
      title: "Clip Editor",
      description: "Opening clip editor for this recording...",
    })
    // In a real app, this would open a clip editor
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-white to-orange-50 dark:from-gray-950 dark:to-gray-900">
        <div className="container mx-auto py-8">
          <div className="animate-pulse space-y-4">
            <div className="h-8 bg-gray-200 rounded w-1/4"></div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {[...Array(6)].map((_, i) => (
                <div key={i} className="bg-gray-200 rounded-lg h-64"></div>
              ))}
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-orange-50 dark:from-gray-950 dark:to-gray-900">
      <div className="container mx-auto py-8">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => router.back()}
              className="hover:bg-orange-100 dark:hover:bg-orange-900/20"
            >
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <div>
              <h1 className="text-3xl font-bold bg-gradient-to-r from-orange-500 to-amber-400 bg-clip-text text-transparent">
                Stream Recordings
              </h1>
              <p className="text-muted-foreground">Watch and manage your recorded live shopping streams</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              onClick={() => router.push("/grocery/live")}
              className="border-orange-200 dark:border-orange-800"
            >
              Back to Live
            </Button>
          </div>
        </div>

        <Tabs defaultValue="all" className="space-y-4">
          <TabsList>
            <TabsTrigger value="all">All Recordings</TabsTrigger>
            <TabsTrigger value="public">Public</TabsTrigger>
            <TabsTrigger value="private">Private</TabsTrigger>
            <TabsTrigger value="processing">Processing</TabsTrigger>
          </TabsList>

          <TabsContent value="all" className="mt-0">
            <RecordedStreamsLibrary
              recordings={recordings}
              onPlay={handlePlayRecording}
              onDownload={handleDownloadRecording}
              onShare={handleShareRecording}
              onCreateClip={handleCreateClip}
            />
          </TabsContent>

          <TabsContent value="public" className="mt-0">
            <RecordedStreamsLibrary
              recordings={recordings.filter((r) => r.isPublic)}
              onPlay={handlePlayRecording}
              onDownload={handleDownloadRecording}
              onShare={handleShareRecording}
              onCreateClip={handleCreateClip}
            />
          </TabsContent>

          <TabsContent value="private" className="mt-0">
            <RecordedStreamsLibrary
              recordings={recordings.filter((r) => !r.isPublic)}
              onPlay={handlePlayRecording}
              onDownload={handleDownloadRecording}
              onShare={handleShareRecording}
              onCreateClip={handleCreateClip}
            />
          </TabsContent>

          <TabsContent value="processing" className="mt-0">
            <RecordedStreamsLibrary
              recordings={recordings.filter((r) => r.isProcessing)}
              onPlay={handlePlayRecording}
              onDownload={handleDownloadRecording}
              onShare={handleShareRecording}
              onCreateClip={handleCreateClip}
            />
          </TabsContent>
        </Tabs>

        {/* Quick Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mt-8">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Recordings</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{recordings.length}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Views</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{recordings.reduce((sum, r) => sum + r.viewCount, 0)}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Downloads</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{recordings.reduce((sum, r) => sum + r.downloadCount, 0)}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Processing</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{recordings.filter((r) => r.isProcessing).length}</div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
