export interface StreamRecording {
  id: string
  streamId: string
  title: string
  description?: string
  thumbnailUrl?: string
  recordingUrl: string
  duration: number // in seconds
  fileSize: number // in bytes
  startTime: string // ISO date string
  endTime?: string // ISO date string
  isProcessing: boolean
  isPublic: boolean
  viewCount: number
  downloadCount: number
  highlights: StreamHighlight[]
  chapters: StreamChapter[]
  quality: "low" | "medium" | "high" | "source"
  format: "mp4" | "webm"
}

export interface StreamChapter {
  id: string
  title: string
  startTime: number // in seconds
  endTime?: number // in seconds
  thumbnailUrl?: string
  productIds?: string[] // products featured in this chapter
}

export interface StreamHighlight {
  id: string
  title: string
  startTime: number // in seconds
  endTime: number // in seconds
  thumbnailUrl?: string
  clipUrl?: string
  viewCount: number
  createdBy: string // user who created the highlight
  isAutoGenerated: boolean
}

export interface DVRState {
  isEnabled: boolean
  bufferDuration: number // in seconds
  currentPosition: number // in seconds
  isRewinding: boolean
  playbackSpeed: number // 1.0 = normal speed
  availableQualities: string[]
  currentQuality: string
}

export interface RecordingControls {
  isRecording: boolean
  isPaused: boolean
  recordingDuration: number // in seconds
  autoRecord: boolean
  recordQuality: "low" | "medium" | "high" | "source"
  saveToCloud: boolean
  createHighlights: boolean
}

export interface Poll {
  id: string
  streamId: string
  question: string
  options: PollOption[]
  status: "draft" | "active" | "ended"
  createdAt: Date
  activatedAt?: Date
  endedAt?: Date
  duration?: number // in seconds, optional for polls that don't auto-close
  allowMultipleChoices: boolean
  isAnonymous: boolean
  totalVotes: number
  highlightedInStream: boolean
}

export interface PollOption {
  id: string
  text: string
  votes: number
  color?: string
}

export interface Quiz {
  id: string
  streamId: string
  title: string
  questions: QuizQuestion[]
  status: "draft" | "active" | "ended"
  createdAt: Date
  activatedAt?: Date
  endedAt?: Date
  timePerQuestion: number // in seconds
  currentQuestionIndex?: number
  isAnonymous: boolean
  showCorrectAnswers: boolean
  showLeaderboard: boolean
  totalParticipants: number
  highlightedInStream: boolean
}

export interface QuizQuestion {
  id: string
  text: string
  options: QuizOption[]
  correctOptionId?: string
  timeLimit?: number // in seconds, overrides quiz default if set
  image?: string
  explanation?: string
}

export interface QuizOption {
  id: string
  text: string
  votes: number
  color?: string
}

export interface UserPollResponse {
  userId: string
  pollId: string
  selectedOptionIds: string[]
  submittedAt: Date
}

export interface UserQuizResponse {
  userId: string
  quizId: string
  answers: {
    questionId: string
    selectedOptionId: string
    isCorrect?: boolean
    timeToAnswer: number // in seconds
  }[]
  score: number
  completedAt?: Date
}

export interface QuizLeaderboard {
  quizId: string
  entries: QuizLeaderboardEntry[]
}

export interface QuizLeaderboardEntry {
  userId: string
  username: string
  userAvatar?: string
  score: number
  timeToComplete?: number // in seconds
  rank: number
}
