"use client"

import ThemeToggle from "@/components/theme-toggle"

export default function AIPolicyPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-950 text-gray-900 dark:text-white">
      {/* Hero Section */}
      <section className="relative py-24 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-white via-orange-50/30 to-white dark:from-gray-950 dark:via-orange-950/30 dark:to-gray-950"></div>
        <div className="absolute inset-0 bg-[url('/grid-pattern.svg')] bg-center opacity-5 dark:opacity-10"></div>

        <div className="container relative z-10 mx-auto px-4">
          <div className="flex justify-end mb-4">
            <ThemeToggle />
          </div>
          <div className="max-w-3xl mx-auto text-center">
            <div className="inline-block mb-6 px-6 py-2 border border-orange-500/30 rounded-full bg-orange-500/10 backdrop-blur-sm">
              <span className="text-orange-600 dark:text-orange-400">Legal</span>
            </div>
            <h1 className="text-4xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-orange-600 via-orange-500 to-yellow-500 dark:from-orange-400 dark:via-orange-300 dark:to-yellow-300 text-transparent bg-clip-text">
              AI Policy
            </h1>
            <p className="text-xl text-gray-700 dark:text-gray-300 mb-8">Last updated: Nov 21, 2025</p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 bg-white dark:bg-gray-950">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto prose prose-gray dark:prose-invert prose-orange">
            <div className="space-y-8">
              <div>
                <h2 className="text-2xl font-bold mb-4">1. Introduction</h2>
                <p>
                  This AI Policy explains how RunAsh uses artificial intelligence and machine learning systems to
                  provide functionality, the types of data involved, the safeguards in place, and your rights and choices.
                  By using our AI-enabled features, you consent to the practices described in this policy in addition to
                  our Privacy Policy and Terms of Service.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">2. Scope</h2>
                <p>
                  This policy covers all AI/ML features provided by RunAsh, including but not limited to real-time
                  audio/video processing, content moderation, personalization, recommendation, and any automated decision
                  systems integrated into the Service.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">3. Data Used by AI Systems</h2>
                <ul>
                  <li>
                    <strong>Input data:</strong> Audio, video, text, metadata, and user-provided content required to
                    operate AI features.
                  </li>
                  <li>
                    <strong>Derived data:</strong> Features, embeddings, transcripts, or summaries generated by our
                    processing pipelines.
                  </li>
                  <li>
                    <strong>Operational data:</strong> Usage metrics, logs, and performance telemetry used to monitor and
                    improve AI models.
                  </li>
                </ul>
                <p>
                  We only process the data necessary to deliver the AI functionality you enable. Streaming audio and
                  video are processed in real time and are not stored long-term unless you explicitly enable recording.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">4. Purpose and Use</h2>
                <p>
                  AI is used to:
                </p>
                <ul>
                  <li>Enhance real-time audio/video quality and provide accessibility features (e.g., live captions).</li>
                  <li>Detect and mitigate harmful content or behavior to keep the platform safe.</li>
                  <li>Personalize user experience and recommendations where enabled.</li>
                  <li>Improve models and services through aggregated, anonymized analytics.</li>
                </ul>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">5. Third-Party Models and Services</h2>
                <p>
                  We may use third-party AI providers to power some features. When we do, we disclose the provider where
                  required and ensure contractual safeguards for data handling. Third-party providers may have their own
                  policies — we encourage you to review them when relevant.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">6. Model Limitations and Risks</h2>
                <p>
                  AI models can make errors, produce biased outputs, or fail to understand context. We recommend users
                  treat AI outputs as assistive and verify critical information independently. We continuously test and
                  update our models to mitigate risks.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">7. User Controls and Choices</h2>
                <ul>
                  <li>
                    <strong>Opt-in / Opt-out:</strong> You can enable or disable AI features in your account or stream
                    settings where applicable.
                  </li>
                  <li>
                    <strong>Recording:</strong> Recording must be explicitly enabled; otherwise, real-time streams are not
                    stored.
                  </li>
                  <li>
                    <strong>Data access and deletion:</strong> You can request access to or deletion of your data under
                    our account settings or by contacting us.
                  </li>
                </ul>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">8. Safety, Moderation, and Abuse Prevention</h2>
                <p>
                  We use automated systems and human review where necessary to detect policy violations, harmful content,
                  or abuse. These systems prioritize user safety and compliance with applicable laws. Suspected
                  violations may result in action on the account, including restrictions or termination.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">9. Data Retention</h2>
                <p>
                  Unless you opt into recording, AI processing is real-time and transient. Logs and aggregated metrics
                  used for improving services may be retained in anonymized or pseudonymized form for analytics and model
                  training according to our retention schedules.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">10. Security and Access</h2>
                <p>
                  We protect AI-related data using industry-standard security measures including encryption in transit
                  and at rest, access controls, and monitoring. Only authorized personnel and systems may access data
                  according to least-privilege principles.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">11. Transparency and Explainability</h2>
                <p>
                  We strive to provide clear information about when AI is being used and the nature of automated
                  decisions. For decisions that have significant effects, we will provide meaningful information about
                  the logic involved where feasible.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">12. Children</h2>
                <p>
                  Our Service is not intended for children under 13. We do not knowingly provide AI features to children
                  under the applicable age without parental consent.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">13. Changes to this Policy</h2>
                <p>
                  We may update this AI Policy as our technology and practices evolve. Material changes will be posted
                  with an updated "Last updated" date.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold mb-4">14. Contact</h2>
                <p>
                  If you have questions about our AI Policy, contact us at legal@runash.in or through the support channels
                  in your account.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
      }
