// Recipe suggestions
   if (input.includes("recipe") || input.includes("cook") || input.includes("meal")) {
     return {
       id: Date.now().toString(),
       content: "Here are some sustainable recipes perfect for your cooking level:",
       role: "assistant",
       timestamp: new Date(),
       type: "recipe",
       metadata: {
         recipes: [
           {
             id: "1",
             name: "Organic Quinoa Buddha Bowl",
             description:
               "A nutritious and colorful bowl with organic quinoa, seasonal vegetables, and tahini dressing",
             difficulty: "easy",
             prepTime: 15,
             cookTime: 20,
             servings: 2,
             ingredients: [
               { id: "1", name: "Organic Quinoa", amount: "1", unit: "cup", isOrganic: true },
               { id: "2", name: "Organic Kale", amount: "2", unit: "cups", isOrganic: true },
               { id: "3", name: "Organic Chickpeas", amount: "1", unit: "can", isOrganic: true },
               { id: "4", name: "Tahini", amount: "3", unit: "tbsp", isOrganic: false },
               { id: "5", name: "Lemon", amount: "1", unit: "whole", isOrganic: true },
               { id: "6", name: "Olive Oil", amount: "2", unit: "tbsp", isOrganic: true },
             ],
             instructions: [
               "Rinse quinoa and cook according to package instructions (1 cup quinoa to 2 cups water)",
               "Massage kale with olive oil and lemon juice for 2-3 minutes until softened",
               "Drain and rinse chickpeas, pat dry",
               "Roast chickpeas at 400°F for 15 minutes with a drizzle of olive oil",
               "Prepare tahini dressing: mix tahini, lemon juice, water, and salt to taste",
               "Assemble bowls: start with quinoa, add kale, chickpeas, and any additional veggies",
               "Drizzle with tahini dressing and serve",
             ],
             image: "/placeholder.svg?height=300&width=400",
             tags: ["vegan", "gluten-free", "high-protein", "sheet pan"],
             sustainabilityScore: 9,
             nutritionalInfo: {
               calories: 420,
               protein: 18,
               carbs: 65,
               fat: 12,
               fiber: 12,
               sugar: 8,
               sodium: 380,
             },
             carbonFootprint: "0.8 kg CO2e",
             wasteReductionTip: "Use vegetable scraps to make homemade broth",
           },
           {
             id: "2",
             name: "One-Pan Sustainable Salmon with Root Vegetables",
             description:
               "Wild-caught salmon roasted with locally-sourced seasonal root vegetables and herbs",
             difficulty: "medium",
             prepTime: 20,
             cookTime: 35,
             servings: 4,
             ingredients: [
               { id: "7", name: "Wild-Caught Salmon Fillets", amount: "4", unit: "pieces", isOrganic: true, isLocal: true },
               { id: "8", name: "Organic Carrots", amount: "4", unit: "medium", isOrganic: true },
               { id: "9", name: "Organic Beets", amount: "3", unit: "medium", isOrganic: true },
               { id: "10", name: "Organic Sweet Potatoes", amount: "2", unit: "medium", isOrganic: true },
               { id: "11", name: "Fresh Rosemary", amount: "2", unit: "tsp", isOrganic: true },
               { id: "12", name: "Lemon", amount: "2", unit: "whole", isOrganic: true },
               { id: "13", name: "Olive Oil", amount: "3", unit: "tbsp", isOrganic: true },
             ],
             instructions: [
               "Preheat oven to 425°F (220°C)",
               "Scrub and chop root vegetables into 1-inch cubes",
               "Toss vegetables with olive oil, rosemary, salt, and pepper",
               "Spread vegetables on a large baking sheet and roast for 20 minutes",
               "Remove from oven, create space for salmon fillets",
               "Place salmon on the pan, drizzle with lemon juice and olive oil",
               "Return to oven and roast for 12-15 minutes until salmon flakes easily",
               "Serve immediately with additional lemon wedges",
             ],
             image: "/placeholder.svg?height=300&width=400",
             tags: ["omega-3", "high-protein", "one-pan", "seasonal", "msc-certified"],
             sustainabilityScore: 8,
             nutritionalInfo: {
               calories: 380,
               protein: 32,
               carbs: 28,
               fat: 18,
               fiber: 6,
               sugar: 10,
               sodium: 240,
             },
             carbonFootprint: "1.2 kg CO2e",
             wasteReductionTip: "Use vegetable peels to make crispy chips - toss with oil and roast separately",
           },
           {
             id: "3",
             name: "Zero-Waste Vegetable Scrap Soup",
             description:
               "A nourishing soup made entirely from vegetable scraps and stems, demonstrating how to minimize kitchen waste",
             difficulty: "easy",
             prepTime: 10,
             cookTime: 45,
             servings: 6,
             ingredients: [
               { id: "14", name: "Onion Peels and Ends", amount: "2", unit: "cups", isOrganic: true },
               { id: "15", name: "Carrot Peels and Tops", amount: "1", unit: "cup", isOrganic: true },
               { id: "16", name: "Celery Leaves and Ends", amount: "1", unit: "cup", isOrganic: true },
               { id: "17", name: "Potato Peels", amount: "1", unit: "cup", isOrganic: true },
               { id: "18", name: "Garlic Cloves (with skins)", amount: "4", unit: "cloves", isOrganic: true },
               { id: "19", name: "Bay Leaves", amount: "2", unit: "whole", isOrganic: true },
               { id: "20", name: "Peppercorns", amount: "1", unit: "tsp", isOrganic: false },
             ],
             instructions: [
               "Collect and wash all vegetable scraps thoroughly",
               "Heat 1 tbsp olive oil in a large pot over medium heat",
               "Add scraps and sauté for 5-7 minutes until fragrant",
               "Add 8 cups of water, bay leaves, and peppercorns",
               "Bring to a boil, then reduce heat and simmer for 30-40 minutes",
               "Strain broth through a fine mesh sieve, pressing on solids to extract flavor",
               "Season with salt to taste",
               "Use immediately or freeze in ice cube trays for future recipes",
             ],
             image: "/placeholder.svg?height=300&width=400",
             tags: ["zero-waste", "vegan", "budget-friendly", "broth", "scrap-to-plate"],
             sustainabilityScore: 10,
             nutritionalInfo: {
               calories: 15,
               protein: 0.5,
               carbs: 3,
               fat: 0,
               fiber: 1,
               sugar: 1,
               sodium: 5,
             },
             carbonFootprint: "0.05 kg CO2e",
             wasteReductionTip: "This IS the waste reduction tip! Freeze scraps throughout the week until you have enough",
           },
           {
             id: "4",
             name: "Plant-Based Lentil Shepherd's Pie",
             description:
               "A hearty and sustainable twist on the classic, using protein-rich lentils and mashed cauliflower instead of potatoes",
             difficulty: "medium",
             prepTime: 30,
             cookTime: 40,
             servings: 6,
             ingredients: [
               { id: "21", name: "Green or Brown Lentils", amount: "2", unit: "cups", isOrganic: true },
               { id: "22", name: "Cauliflower", amount: "1", unit: "large head", isOrganic: true },
               { id: "23", name: "Organic Mixed Vegetables", amount: "2", unit: "cups", isOrganic: true },
               { id: "24", name: "Onions", amount: "2", unit: "medium", isOrganic: true },
               { id: "25", name: "Garlic", amount: "4", unit: "cloves", isOrganic: true },
               { id: "26", name: "Vegetable Broth", amount: "4", unit: "cups", isOrganic: false },
               
              ],
             instructions: [
               "Collect and wash all vegetable scraps thoroughly",
               "Heat 1 tbsp olive oil in a large pot over medium heat",
               "Add scraps and sauté for 5-7 minutes until fragrant",
               "Add 8 cups of water, bay leaves, and peppercorns",
               "Bring to a boil, then reduce heat and simmer for 30-40 minutes",
               "Strain broth through a fine mesh sieve, pressing on solids to extract flavor",
               "Season with salt to taste",
               "Use immediately or freeze in ice cube trays for future recipes",
             ],
             image: "/placeholder.svg?height=300&width=400",
             tags: ["zero-waste", "vegan", "budget-friendly", "broth", "scrap-to-plate"],
             sustainabilityScore: 10,
             nutritionalInfo: {
               calories: 15,
               protein: 0.5,
               carbs: 3,
               fat: 0,
               fiber: 1,
               sugar: 1,
               sodium: 5,
             },
             carbonFootprint: "0.05 kg CO2e",
             wasteReductionTip: "This IS the waste reduction tip! Freeze scraps throughout the week until you have enough",
           },
           // Recipe suggestions
            {
              id: "5",
              name: "Organic Overnight Oats with Seasonal Berries",
              description:
                "A make-ahead breakfast featuring organic oats, plant-based milk, and fresh seasonal berries",
              difficulty: "easy",
              prepTime: 5,
              cookTime: 0,
              servings: 2,
              ingredients: [
                { id: "28", name: "Organic Rolled Oats", amount: "1", unit: "cup", isOrganic: true },
                { id: "29", name: "Organic Almond Milk", amount: "1", unit: "cup", isOrganic: true },
                { id: "30", name: "Organic Chia Seeds", amount: "2", unit: "tbsp", isOrganic: true },
                { id: "31", name: "Organic Maple Syrup", amount: "1", unit: "tbsp", isOrganic: true },
                { id: "32", name: "Organic Seasonal Berries", amount: "1", unit: "cup", isOrganic: true },
                { id: "33", name: "Organic Vanilla Extract", amount: "1", unit: "tsp", isOrganic: true },
              ],
              instructions: [
                "In a mason jar or bowl, combine oats, chia seeds, and almond milk",
                "Add maple syrup and vanilla extract, stir well",
                "Cover and refrigerate overnight (or minimum 4 hours)",
                "In the morning, stir and add more milk if needed for desired consistency",
                "Top with fresh berries and optional nuts or seeds",
                "Enjoy cold or warm slightly if preferred",
              ],
              image: "/placeholder.svg?height=300&width=400",
              tags: ["vegan", "gluten-free option", "no-cook", "make-ahead", "breakfast"],
              sustainabilityScore: 9,
              nutritionalInfo: {
                calories: 280,
                protein: 8,
                carbs: 48,
                fat: 9,
                fiber: 10,
                sugar: 12,
                sodium: 85,
              },
              carbonFootprint: "0.3 kg CO2e",
              wasteReductionTip: "Buy oats in bulk using reusable containers to eliminate packaging waste",
            },
            {
              id: "6",
              name: "Organic Kale & Avocado Superfood Salad",
              description:
                "A nutrient-dense salad featuring organic kale, creamy avocado, and a zesty lemon-tahini dressing",
              difficulty: "easy",
              prepTime: 15,
              cookTime: 0,
              servings: 4,
              ingredients: [
                { id: "34", name: "Organic Kale", amount: "8", unit: "cups", isOrganic: true },
                { id: "35", name: "Organic Avocados", amount: "2", unit: "whole", isOrganic: true },
                { id: "36", name: "Organic Cherry Tomatoes", amount: "1", unit: "cup", isOrganic: true },
                { id: "37", name: "Organic Red Onion", amount: "1/2", unit: "medium", isOrganic: true },
                { id: "38", name: "Organic Hemp Seeds", amount: "3", unit: "tbsp", isOrganic: true },
                { id: "39", name: "Organic Lemon", amount: "2", unit: "whole", isOrganic: true },
                { id: "40", name: "Organic Tahini", amount: "2", unit: "tbsp", isOrganic: true },
              ],
              instructions: [
                "Wash kale thoroughly and remove tough stems",
                "Chop kale into bite-sized pieces and place in large bowl",
                "Massage kale with a pinch of salt for 3-4 minutes until tender",
                "Dice avocados, halve cherry tomatoes, and thinly slice red onion",
                "Add all vegetables to the kale",
                "Whisk together lemon juice, tahini, and 2 tbsp water for dressing",
                "Toss salad with dressing and top with hemp seeds",
                "Let marinate 10 minutes before serving",
              ],
              image: "/placeholder.svg?height=300&width=400",
              tags: ["raw", "vegan", "gluten-free", "no-cook", "superfood"],
              sustainabilityScore: 10,
              nutritionalInfo: {
                calories: 240,
                protein: 7,
                carbs: 18,
                fat: 18,
                fiber: 8,
                sugar: 4,
                sodium: 95,
              },
              carbonFootprint: "0.4 kg CO2e",
              wasteReductionTip: "Compost kale stems or blend them into smoothies for extra fiber",
            },
            {
              id: "7",
              name: "Organic Chickpea Pasta with Basil Pesto",
              description:
                "Protein-rich chickpea pasta tossed in fresh organic basil pesto, cherry tomatoes, and nutritional yeast",
              difficulty: "medium",
              prepTime: 20,
              cookTime: 15,
              servings: 4,
              ingredients: [
                { id: "41", name: "Organic Chickpea Pasta", amount: "12", unit: "oz", isOrganic: true },
                { id: "42", name: "Organic Fresh Basil", amount: "2", unit: "cups", isOrganic: true },
                { id: "43", name: "Organic Cherry Tomatoes", amount: "1.5", unit: "cups", isOrganic: true },
                ],
                instructions: [
                "Rinse quinoa and cook according to package instructions (1 cup quinoa to 2 cups water)",
                "Massage kale with olive oil and lemon juice for 2-3 minutes until softened",
                "Drain and rinse chickpeas, pat dry",
                "Roast chickpeas at 400°F for 15 minutes with a drizzle of olive oil",
                "Prepare tahini dressing: mix tahini, lemon juice, water, and salt to taste",
                "Assemble bowls: start with quinoa, add kale, chickpeas, and any additional veggies",
                "Drizzle with tahini dressing and serve",
              ],
              image: "/placeholder.svg?height=300&width=400",
              tags: ["vegan", "gluten-free", "high-protein", "sheet pan"],
              sustainabilityScore: 9,
              nutritionalInfo: {
                calories: 420,
                protein: 18,
                carbs: 65,
                fat: 12,
                fiber: 12,
                sugar: 8,
                sodium: 380,
              },
              carbonFootprint: "0.8 kg CO2e",
              wasteReductionTip: "Use vegetable scraps to make homemade broth",
            },
                 {
  id: "7",
  name: "Organic Chickpea Pasta with Basil Pesto",
  description:
    "Protein-rich chickpea pasta tossed in fresh organic basil pesto, cherry tomatoes, and nutritional yeast",
  difficulty: "medium",
  prepTime: 20,
  cookTime: 15,
  servings: 4,
  ingredients: [
    { id: "41", name: "Organic Chickpea Pasta", amount: "12", unit: "oz", isOrganic: true },
    { id: "42", name: "Organic Fresh Basil", amount: "2", unit: "cups", isOrganic: true },
    { id: "43", name: "Organic Cherry Tomatoes", amount: "1.5", unit: "cups", isOrganic: true },
    { id: "44", name: "Organic Pine Nuts", amount: "1/3", unit: "cup", isOrganic: true },
    { id: "45", name: "Organic Garlic", amount: "3", unit: "cloves", isOrganic: true },
    { id: "46", name: "Organic Lemon", amount: "1", unit: "whole", isOrganic: true },
    { id: "47", name: "Organic Extra Virgin Olive Oil", amount: "1/2", unit: "cup", isOrganic: true },
    { id: "48", name: "Nutritional Yeast", amount: "1/4", unit: "cup", isOrganic: false },
  ],
  instructions: [
    "Bring a large pot of salted water to boil",
    "Cook chickpea pasta according to package directions (usually 8-10 minutes)",
    "While pasta cooks, make pesto: blend basil, pine nuts, garlic, lemon juice, and olive oil",
    "Halve the cherry tomatoes",
    "Reserve 1/2 cup pasta water, then drain pasta",
    "Return pasta to pot with pesto, tomatoes, and nutritional yeast",
    "Add pasta water gradually to achieve desired sauce consistency",
    "Toss everything together and serve warm",
  ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["vegan", "gluten-free", "high-protein", "nut-free option", "main dish"],
  sustainabilityScore: 8,
  nutritionalInfo: {
    calories: 420,
    protein: 20,
    carbs: 48,
    fat: 18,
    fiber: 12,
    sugar: 4,
    sodium: 320,
  },
  carbonFootprint: "0.6 kg CO2e",
  wasteReductionTip: "Regrow basil from stems - place in water until roots form, then plant in soil",
},
{
  id: "8",
  name: "Organic Spiced Lentil & Sweet Potato Bowl",
  description:
    "Warm and comforting organic red lentils simmered with sweet potatoes, coconut milk, and aromatic spices",
  difficulty: "easy",
  prepTime: 10,
  cookTime: 30,
  servings: 6,
  ingredients: [
    { id: "49", name: "Organic Red Lentils", amount: "1.5", unit: "cups", isOrganic: true },
    { id: "50", name: "Organic Sweet Potatoes", amount: "2", unit: "large", isOrganic: true },
    { id: "51", name: "Organic Coconut Milk", amount: "1", unit: "can", isOrganic: true },
    { id: "52", name: "Organic Onion", amount: "1", unit: "medium", isOrganic: true },
    { id: "53", name: "Organic Ginger", amount: "1", unit: "inch", isOrganic: true },
    { id: "54", name: "Organic Turmeric", amount: "1", unit: "tsp", isOrganic: true },
    { id: "55", name: "Organic Cumin", amount: "1", unit: "tsp", isOrganic: true },
    { id: "56", name: "Organic Vegetable Broth", amount: "4", unit: "cups", isOrganic: true },
  ],
  instructions: [
    "Dice sweet potatoes into 1-inch cubes",
    "Finely chop onion and grate ginger",
    "Rinse lentils thoroughly until water runs clear",
    "In a large pot, sauté onion with a splash of oil until translucent",
    "Add ginger, turmeric, and cumin, cook for 1 minute until fragrant",
    "Add lentils, sweet potatoes, and vegetable broth",
    "Bring to boil, then simmer covered for 20 minutes",
    "Stir in coconut milk and simmer 5 more minutes",
    "Mash some sweet potato pieces for creaminess if desired",
    "Season with salt and serve over organic rice or quinoa",
  ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["vegan", "gluten-free", "anti-inflammatory", "comfort food", "freezer-friendly"],
  sustainabilityScore: 9,
  nutritionalInfo: {
    calories: 285,
    protein: 14,
    carbs: 45,
    fat: 8,
    fiber: 9,
    sugar: 6,
    sodium: 420,
  },
  carbonFootprint: "0.5 kg CO2e",
  wasteReductionTip: "Use the thick coconut milk at the top of the can for the recipe, thin remaining with water for smoothies",
},
{
  id: "9",
  name: "Organic No-Bake Energy Balls",
  description:
    "Quick and nutritious snack balls made with organic dates, oats, almond butter, and dark chocolate chips",
  difficulty: "easy",
  prepTime: 15,
  cookTime: 0,
  servings: 20,
  ingredients: [
    { id: "57", name: "Organic Medjool Dates", amount: "1.5", unit: "cups", isOrganic: true },
    { id: "58", name: "Organic Rolled Oats", amount: "1", unit: "cup", isOrganic: true },
    { id: "59", name: "Organic Almond Butter", amount: "1/2", unit: "cup", isOrganic: true },
    { id: "60", name: "Organic Dark Chocolate Chips", amount: "1/3", unit: "cup", isOrganic: true },
    { id: "61", name: "Organic Chia Seeds", amount: "2", unit: "tbsp", isOrganic: true },
    { id: "62", name: "Organic Vanilla Extract", amount: "1", unit: "tsp", isOrganic: true },
    { id: "63", name: "Sea Salt", amount: "1/8", unit: "tsp", isOrganic: false },
  ],
  instructions: [
    "Remove pits from dates if not already pitted",
    "Soak dates in warm water for 5 minutes if very dry, then drain",
    "Pulse oats in food processor until slightly broken down",
    "Add dates and pulse until a sticky dough forms",
    "Add almond butter, chia seeds, vanilla, and salt",
    "Pulse until mixture sticks together when pressed",
    "Transfer to bowl and fold in chocolate chips",
    "Roll into 1-inch balls using your hands",
    "Place on parchment-lined tray",
    "Chill in refrigerator for 30 minutes to firm up",
    "Store in airtight container in fridge for up to 2 weeks",
  ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["vegan", "gluten-free", "no-bake", "snack", "kid-friendly", "freezer-friendly"],
  sustainabilityScore: 8,
  nutritionalInfo: {
    calories: 95,
    protein: 2,
    carbs: 14,
    fat: 4,
    fiber: 2,
    sugar: 9,
    sodium: 15,
  },
  carbonFootprint: "0.2 kg CO2e",
  wasteReductionTip: "Buy dates and oats in bulk, store in glass jars; use parchment paper multiple times",
},
// Continuing from id:10...
{
  id: "10",
  name: "Organic Creamy Mushroom & Spinach Risotto",
  description:
    "Creamy arborio rice cooked with organic mushrooms, fresh spinach, and finished with nutritional yeast",
  difficulty: "advanced",
  prepTime: 15,
  cookTime: 35,
  servings: 4,
  ingredients: [
    { id: "64", name: "Organic Arborio Rice", amount: "1.5", unit: "cups", isOrganic: true },
    { id: "65", name: "Organic Mixed Mushrooms", amount: "1", unit: "lb", isOrganic: true },
    { id: "66", name: "Organic Fresh Spinach", amount: "4", unit: "cups", isOrganic: true },
    { id: "67", name: "Organic Vegetable Broth", amount: "5", unit: "cups", isOrganic: true },
    { id: "68", name: "Organic White Wine", amount: "1/2", unit: "cup", isOrganic: true },
    { id: "69", name: "Organic Shallots", amount: "2", unit: "medium", isOrganic: true },
    { id: "70", name: "Nutritional Yeast", amount: "1/4", unit: "cup", isOrganic: false },
  ],
  instructions: [
    "Warm vegetable broth in a saucepan and keep at a low simmer",
    "Clean and slice mushrooms, mince shallots",
    "Heat olive oil in a large skillet over medium heat",
    "Sauté mushrooms until browned, about 8 minutes, then remove and set aside",
    "In same pan, add more oil and sauté shallots until translucent",
    "Add arborio rice and toast for 2 minutes until grains are translucent at edges",
    "Pour in white wine and stir until fully absorbed",
    "Add warm broth one ladle at a time, stirring constantly until absorbed",
    "Continue adding broth and stirring for 25-30 minutes until rice is creamy and al dente",
    "Stir in spinach, mushrooms, and nutritional yeast",
    "Let sit 2 minutes, then serve immediately",
  ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["vegan", "gluten-free", "comfort food", "advanced technique", "impressive"],
  sustainabilityScore: 9,
  nutritionalInfo: {
    calories: 340,
    protein: 12,
    carbs: 58,
    fat: 8,
    fiber: 4,
    sugar: 3,
    sodium: 480,
  },
  carbonFootprint: "0.7 kg CO2e",
  wasteReductionTip: "Save mushroom stems to add to vegetable scrap broth; use wine from a box to reduce bottle waste",
},
{
  id: "11",
  name: "Organic Baked Falafel Bowl",
  description: "Crispy baked falafel made from organic chickpeas, served with quinoa and tahini dressing",
  difficulty: "medium",
  prepTime: 45,
  cookTime: 25,
  servings: 4,
  ingredients: [
    { id: "71", name: "Organic Dried Chickpeas", amount: "1.5", unit: "cups", isOrganic: true },
    { id: "72", name: "Organic Parsley", amount: "1", unit: "cup", isOrganic: true },
    { id: "73", name: "Organic Cilantro", amount: "1/2", unit: "cup", isOrganic: true },
    { id: "74", name: "Organic Garlic", amount: "4", unit: "cloves", isOrganic: true },
    { id: "75", name: "Organic Onion", amount: "1", unit: "medium", isOrganic: true },
    { id: "76", name: "Organic Quinoa", amount: "1", unit: "cup", isOrganic: true },
    { id: "77", name: "Organic Tahini", amount: "3", unit: "tbsp", isOrganic: true },
  ],
  instructions: [
    "Soak chickpeas in water for 24 hours, then drain and rinse",
    "Cook quinoa according to package directions",
    "Pulse chickpeas in food processor until coarsely ground",
    "Add herbs, garlic, onion, cumin, and pulse until mixture holds together",
    "Form into 16 small patties and place on parchment-lined baking sheet",
    "Brush lightly with olive oil",
    "Bake at 400°F for 20-25 minutes, flipping halfway through",
    "Whisk together tahini, lemon juice, and water for dressing",
    "Serve falafel over quinoa with dressing and fresh vegetables",
  ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["vegan", "gluten-free", "high-protein", "make-ahead", "meal-prep"],
  sustainabilityScore: 9,
  nutritionalInfo: {
    calories: 380,
    protein: 18,
    carbs: 52,
    fat: 14,
    fiber: 12,
    sugar: 6,
    sodium: 320,
  },
  carbonFootprint: "0.6 kg CO2e",
  wasteReductionTip: "Use aquafaba (chickpea soaking liquid) as egg substitute in other recipes",
},
{
  id: "12",
  name: "Organic Green Smoothie Bowl",
  description: "Thick smoothie bowl made with organic spinach, mango, banana, and topped with superfoods",
  difficulty: "easy",
  prepTime: 10,
  cookTime: 0,
  servings: 2,
  ingredients: [
    { id: "78", name: "Organic Frozen Mango", amount: "1.5", unit: "cups", isOrganic: true },
    { id: "79", name: "Organic Frozen Banana", amount: "2", unit: "medium", isOrganic: true },
    { id: "80", name: "Organic Spinach", amount: "2", unit: "cups", isOrganic: true },
    { id: "81", name: "Organic Coconut Milk", amount: "1/2", unit: "cup", isOrganic: true },
    { id: "82", name: "Organic Chia Seeds", amount: "2", unit: "tbsp", isOrganic: true },
    { id: "83", name: "Organic Granola", amount: "1/4", unit: "cup", isOrganic: true },
  ],
  instructions: [
    "Add frozen mango, banana, spinach, and coconut milk to blender",
    "Blend on high until thick and creamy, adding more milk if needed",
    "Pour into bowls",
    "Top with chia seeds, granola, fresh berries, and coconut flakes",
    "Serve immediately with spoon",
  ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["vegan", "gluten-free", "no-cook", "breakfast", "raw", "superfood"],
  sustainabilityScore: 9,
  nutritionalInfo: {
    calories: 285,
    protein: 6,
    carbs: 48,
    fat: 10,
    fiber: 8,
    sugar: 32,
    sodium: 45,
  },
  carbonFootprint: "0.4 kg CO2e",
  wasteReductionTip: "Freeze overripe bananas and imperfect spinach to prevent food waste",
},
{
  id: "13",
  name: "Organic Thai Coconut Vegetable Curry",
  description: "Aromatic red curry with organic seasonal vegetables, coconut milk, and fresh herbs",
  difficulty: "easy",
  prepTime: 20,
  cookTime: 25,
  servings: 6,
  ingredients: [
    { id: "84", name: "Organic Coconut Milk", amount: "2", unit: "cans", isOrganic: true },
    { id: "85", name: "Organic Mixed Vegetables", amount: "4", unit: "cups", isOrganic: true },
    { id: "86", name: "Organic Tofu", amount: "14", unit: "oz", isOrganic: true },
    { id: "87", name: "Organic Red Curry Paste", amount: "3", unit: "tbsp", isOrganic: true },
    { id: "88", name: "Organic Ginger", amount: "1", unit: "inch", isOrganic: true },
    { id: "89", name: "Organic Garlic", amount: "4", unit: "cloves", isOrganic: true },
    { id: "90", name: "Organic Lime", amount: "2", unit: "whole", isOrganic: true },
    { id: "91", name: "Organic Fresh Basil", amount: "1", unit: "cup", isOrganic: true },
  ],
  instructions: [
    "Press tofu for 15 minutes, then cut into cubes",
    "Chop vegetables into bite-sized pieces",
    "Mince garlic and grate ginger",
    "Heat oil in large pan over medium heat",
    "Sauté garlic and ginger for 1 minute",
    "Add curry paste and cook for 2 minutes until fragrant",
    "Pour in coconut milk and bring to simmer",
    "Add vegetables and tofu, cook for 15-20 minutes until tender",
    "Stir in lime juice and fresh basil",
    "Serve over organic jasmine rice",
  ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["vegan", "gluten-free", "coconut-free option", "comfort food", "one-pot"],
  sustainabilityScore: 8,
  nutritionalInfo: {
    calories: 265,
    protein: 12,
    carbs: 18,
    fat: 18,
    fiber: 5,
    sugar: 6,
    sodium: 520,
  },
  carbonFootprint: "0.8 kg CO2e",
  wasteReductionTip: "Use vegetable stems in curry and keep herb stems to flavor broth later",
},
{
  id: "14",
  name: "Organic Stuffed Bell Peppers",
  description: "Colorful organic bell peppers stuffed with quinoa, black beans, corn, and Mexican spices",
  difficulty: "medium",
  prepTime: 25,
  cookTime: 45,
  servings: 6,
  ingredients: [
    { id: "92", name: "Organic Bell Peppers", amount: "6", unit: "whole", isOrganic: true },
    { id: "93", name: "Organic Quinoa", amount: "1", unit: "cup", isOrganic: true },
    { id: "94", name: "Organic Black Beans", amount: "1", unit: "can", isOrganic: true },
    { id: "95", name: "Organic Corn", amount: "1", unit: "cup", isOrganic: true },
    { id: "96", name: "Organic Diced Tomatoes", amount: "1", unit: "can", isOrganic: true },
    { id: "97", name: "Organic Chili Powder", amount: "2", unit: "tsp", isOrganic: true },
    { id: "98", name: "Organic Cumin", amount: "1", unit: "tsp", isOrganic: true },
  ],
  instructions: [
    "Preheat oven to 375°F",
    "Cut tops off peppers and remove seeds",
    "Cook quinoa according to package directions",
    "In large bowl, mix quinoa, drained beans, corn, tomatoes, and spices",
    "Stuff mixture evenly into peppers",
    "Place peppers in baking dish with 1/2 inch water",
    "Cover with foil and bake 35 minutes",
    "Remove foil and bake 10 more minutes",
    "Top with avocado or cashew cream if desired",
  ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["vegan", "gluten-free", "high-fiber", "meal-prep", "freezer-friendly"],
  sustainabilityScore: 9,
  nutritionalInfo: {
    calories: 220,
    protein: 10,
    carbs: 42,
    fat: 3,
    fiber: 9,
    sugar: 8,
    sodium: 280,
  },
  carbonFootprint: "0.5 kg CO2e",
  wasteReductionTip: "Use pepper tops in salads or chop and freeze for future recipes",
},
{
  id: "15",
  name: "Organic Blueberry Almond Muffins",
  description: "Light and fluffy muffins made with organic almond flour, fresh blueberries, and maple syrup",
  difficulty: "easy",
  prepTime: 15,
  cookTime: 25,
  servings: 12,
  ingredients: [
    { id: "99", name: "Organic Almond Flour", amount: "2", unit: "cups", isOrganic: true },
    { id: "100", name: "Organic Fresh Blueberries", amount: "1.5", unit: "cups", isOrganic: true },
    { id: "101", name: "Organic Maple Syrup", amount: "1/2", unit: "cup", isOrganic: true },
    { id: "102", name: "Organic Eggs", amount: "3", unit: "large", isOrganic: true },
    { id: "103", name: "Organic Coconut Oil", amount: "1/4", unit: "cup", isOrganic: true },
    { id: "104", name: "Organic Vanilla Extract", amount: "1", unit: "tsp", isOrganic: true },
    { id: "105", name: "Baking Powder", amount: "1", unit: "tsp", isOrganic: false },
  ],
  instructions: [
    "Preheat oven to 350°F and line muffin tin",
    "Whisk together almond flour and baking powder",
    "In another bowl, whisk eggs, maple syrup, melted coconut oil, and vanilla",
    "Combine wet and dry ingredients gently",
    "Fold in blueberries",
    "Divide batter among muffin cups",
    "Bake 22-25 minutes until golden",
    "Cool on wire rack before serving",
  ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["gluten-free", "paleo", "kid-friendly", "snack", "breakfast"],
  sustainabilityScore: 7,
  nutritionalInfo: {
    calories: 180,
    protein: 5,
    carbs: 18,
    fat: 11,
    fiber: 3,
    sugar: 10,
    sodium: 95,
  },
  carbonFootprint: "0.6 kg CO2e",
  wasteReductionTip: "Use blueberry stems and imperfect berries to make infused water",
},
{
  id: "16",
  name: "Organic Carrot Ginger Soup",
  description: "Smooth and warming soup made with organic carrots, fresh ginger, and coconut cream",
  difficulty: "easy",
  prepTime: 15,
  cookTime: 30,
  servings: 4,
  ingredients: [
    { id: "106", name: "Organic Carrots", amount: "2", unit: "lbs", isOrganic: true },
    { id: "107", name: "Organic Ginger", amount: "2", unit: "inches", isOrganic: true },
    { id: "108", name: "Organic Onion", amount: "1", unit: "large", isOrganic: true },
    { id: "109", name: "Organic Coconut Cream", amount: "1/2", unit: "cup", isOrganic: true },
    { id: "110", name: "Organic Vegetable Broth", amount: "4", unit: "cups", isOrganic: true },
    { id: "111", name: "Organic Coconut Oil", amount: "2", unit: "tbsp", isOrganic: true },
  ],
  instructions: [
    "Peel and chop carrots into 1-inch pieces",
    "Dice onion and grate ginger",
    "Heat oil in large pot over medium heat",
    "Sauté onion until translucent, about 5 minutes",
    "Add ginger and cook 1 minute",
    ],
  image: "/placeholder.svg?height=300&width=400",
  tags: ["gluten-free", "paleo", "kid-friendly", "snack", "breakfast"],
  sustainabilityScore: 7,
  nutritionalInfo: {
    calories: 180,
    protein: 5,
    carbs: 18,
    fat: 11,
    fiber: 3,
    sugar: 10,
    sodium: 95,
  },
  carbonFootprint: "0.6 kg CO2e",
  wasteReductionTip: "Use blueberry stems and imperfect berries to make infused water",
   },
    },
   ],
  },
 }
}
          
