import type { BackgroundImage } from "@/types/virtual-backgrounds"

export const mockBackgrounds: BackgroundImage[] = [
  {
    id: "bg-1",
    name: "Modern Office",
    url: "/backgrounds/office-modern.jpg",
    thumbnailUrl: "/backgrounds/office-modern.jpg",
    category: ["office"],
    tags: ["professional", "modern", "clean"],
    isPremium: false,
    isNew: false,
    createdAt: "2023-05-15T10:30:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 1250,
  },
  {
    id: "bg-2",
    name: "Abstract Orange",
    url: "/backgrounds/abstract-orange.jpg",
    thumbnailUrl: "/backgrounds/abstract-orange.jpg",
    category: ["abstract"],
    tags: ["colorful", "vibrant", "creative"],
    isPremium: false,
    isNew: false,
    createdAt: "2023-05-10T14:20:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 980,
  },
  {
    id: "bg-3",
    name: "Tech Workspace",
    url: "/backgrounds/tech-workspace.jpg",
    thumbnailUrl: "/backgrounds/tech-workspace.jpg",
    category: ["tech", "office"],
    tags: ["professional", "modern", "tech"],
    isPremium: true,
    isNew: false,
    createdAt: "2023-05-05T09:15:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 1560,
  },
  {
    id: "bg-4",
    name: "Warm Gradient",
    url: "/backgrounds/gradient-warm.jpg",
    thumbnailUrl: "/backgrounds/gradient-warm.jpg",
    category: ["gradients"],
    tags: ["colorful", "warm", "minimal"],
    isPremium: false,
    isNew: true,
    createdAt: "2023-06-01T16:45:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 750,
  },
  {
    id: "bg-5",
    name: "Library",
    url: "/backgrounds/library.jpg",
    thumbnailUrl: "/backgrounds/library.jpg",
    category: ["office"],
    tags: ["professional", "calm", "academic"],
    isPremium: true,
    isNew: false,
    createdAt: "2023-04-20T11:30:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 1120,
  },
  {
    id: "bg-6",
    name: "Minimal Desk",
    url: "/backgrounds/minimal-desk.jpg",
    thumbnailUrl: "/backgrounds/minimal-desk.jpg",
    category: ["minimal", "office"],
    tags: ["clean", "minimal", "professional"],
    isPremium: false,
    isNew: true,
    createdAt: "2023-06-05T13:10:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 680,
  },
  {
    id: "bg-7",
    name: "Office Bookshelf",
    url: "/backgrounds/office-bookshelf.jpg",
    thumbnailUrl: "/backgrounds/office-bookshelf.jpg",
    category: ["office"],
    tags: ["professional", "academic", "clean"],
    isPremium: true,
    isNew: false,
    createdAt: "2023-04-15T10:20:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 1340,
  },
  {
    id: "bg-8",
    name: "Office Window",
    url: "/backgrounds/office-window.jpg",
    thumbnailUrl: "/backgrounds/office-window.jpg",
    category: ["office"],
    tags: ["professional", "bright", "modern"],
    isPremium: false,
    isNew: false,
    createdAt: "2023-05-12T09:40:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 920,
  },
  {
    id: "bg-9",
    name: "Nature Forest",
    url: "/backgrounds/nature-forest.jpg",
    thumbnailUrl: "/backgrounds/nature-forest.jpg",
    category: ["nature"],
    tags: ["calm", "green", "natural"],
    isPremium: false,
    isNew: false,
    createdAt: "2023-05-08T15:30:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 1480,
  },
  {
    id: "bg-10",
    name: "Nature Mountains",
    url: "/backgrounds/nature-mountains.jpg",
    thumbnailUrl: "/backgrounds/nature-mountains.jpg",
    category: ["nature"],
    tags: ["calm", "scenic", "majestic"],
    isPremium: true,
    isNew: false,
    createdAt: "2023-04-25T14:15:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 1680,
  },
  {
    id: "bg-11",
    name: "Blue Abstract",
    url: "/backgrounds/abstract-blue.jpg",
    thumbnailUrl: "/backgrounds/abstract-blue.jpg",
    category: ["abstract"],
    tags: ["colorful", "cool", "creative"],
    isPremium: false,
    isNew: true,
    createdAt: "2023-06-02T11:20:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 580,
  },
  {
    id: "bg-12",
    name: "Geometric Abstract",
    url: "/backgrounds/abstract-geometric.jpg",
    thumbnailUrl: "/backgrounds/abstract-geometric.jpg",
    category: ["abstract"],
    tags: ["modern", "geometric", "minimal"],
    isPremium: true,
    isNew: false,
    createdAt: "2023-04-18T13:40:00Z",
    dimensions: { width: 1920, height: 1080 },
    downloadCount: 1240,
  },
]
